sudo: required
services:
  - docker

before_install:
  - docker build -t fabioaromanini/test-docker-travis-aws-ci -f Dockerfile.test .

script:
  - docker run fabioaromanini/test-docker-travis-aws-ci
